#ifndef _CORE_INPUT_ENUM_HPP_
#define _CORE_INPUT_ENUM_HPP_

/******************************************************************************
**	Includes
******************************************************************************/
#include <Core/Math/Vector2.hpp>
#include <Windows.h>

/******************************************************************************
**	Class Declaration
******************************************************************************/
namespace Gorilla { namespace EInput
{
	struct Keyboard
	{
		enum Type : uint8
		{
			A					,
			B					,
			C					,
			D					,
			E					,
			F					,
			G					,
			H					,
			I					,
			J					,
			K					,
			L					,
			M					,
			N					,
			O					,
			P					,
			Q					,
			R					,
			S					,
			T					,
			U					,
			V					,
			W					,
			X					,
			Y					,
			Z					,
			Numeric1			,
			Numeric2			,
			Numeric3			,
			Numeric4			,
			Numeric5			,
			Numeric6			,
			Numeric7			,
			Numeric8			,
			Numeric9			,
			Numeric0			,
			Escape				,
			F1					,
			F2					,
			F3					,
			F4					,
			F5					,
			F6					,
			F7					,
			F8					,
			F9					,
			F10					,
			F11					,
			F12					,
			Up					= VK_UP,
			Right				= VK_RIGHT,
			Down				= VK_DOWN,
			Left				= VK_LEFT,
			Minus				,
			Equals				,
			Back				,
			Tabulation			,
			Return				,
			BracketLeft			,
			BracketRight		,
			ControlLeft			,
			ControlRight		,
			AlternativeLeft		,
			ShiftLeft			,
			ShiftRight			,

			Lwin				,
			Rwin				,
			Rmenu				,

			Semicolon			,
			Apostrophe			,
			Grave				,		
			Backslash			,		
			Comma				,		
			Period				,
			Slash				,	
			Multiply			,
			Divide				,
			Space				,
			Capital				,	
			Numlock				,
			Scroll				,
			Home				,	
			Prior				,	
			End					,			
			Next				,
			Insert				,
			Delete				,
			NumericPad0         ,
			NumericPad1         ,
			NumericPad2         ,
			NumericPad3         ,
			NumericPad4         ,
			NumericPad5         ,
			NumericPad6         ,
			NumericPad7			,
			NumericPad8			,
			NumericPad9			,
			NumericPadSubtract  ,
			NumericPadAdd       ,
			NumericPadPoint     ,		
			Numpadequals		,	
			NumericPadEnter     ,
			NumericPadComma     ,
		};
	};
}}
#endif